#!/usr/bin/env bash

echo "Configuring database"

export PGPASSWORD='node_password'

#
# Should grab your username
#
dropdb -U $USER chatcryption_db;
createdb -U $USER chatcryption_db;
psql -U $USER chatcryption_db < ./config/db.sql

echo "chatcryption was configured";

// node ./config/asyncFakeData.js

echo "I am done I think!! :)";


CREATE TABLE users (
  user_id SERIAL PRIMARY KEY,
  username VARCHAR,
  password VARCHAR,
  last_login TIMESTAMP
);

CREATE TABLE messages (
  message_id SERIAL PRIMARY KEY,
  author_id VARCHAR REFERENCES users(user_id),
  recipient_id VARCHAR REFERENCES message_recipients(recipient_id)
  message_body VARCHAR(280)
  time_sent TIMESTAMP
);

CREATE TABLE message_recipients (
  recipient_id SERIAL PRIMARY KEY REFERENCES users(user_id),
  message_id INTEGER REFERENCES messages(message_id),
  is_read BOOLEAN,
);